[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@openzeppelin/=node_modules/@openzeppelin/', 'aztec/=src/aztec/', 'aave/=src/bridges/aave/']
fuzz_runs = 1
gas_reports = ["*"]
solc_version = '0.8.10'
auto_detect_solc = false
ETH_RPC_URL = 'https://mainnet.infura.io/v3/760c0f52babd4c3095d9bba255b9479b'
# See more config options https://github.com/gakonst/foundry/tree/master/config